# This is a workflow to build and deploy LaTeX sources

name: Build PDF from LaTeX
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build PDF documents from LaTeX
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: latexmk

      - name: Upload PDF documents
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: build/*.pdf

  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: pdf

      - name: List available files
        run: ls

      - name: Generate version
        id: generate_version
        run: echo "::set-output name=version::$(date +'%Y.%m.%d')"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Curriculum vitae v${{ steps.generate_version.outputs.version }}
          files: "*.pdf"
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
