name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Fix checkout in container (See https://github.com/actions/checkout/issues/1169)
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"

      - name: Generate gitinfo2 data
        run: ./third_party/gitinfo2/post-xxx-sample.sh && cat .git/gitHeadInfo.gin

      - name: Build PDF documents with latexmk
        run: latexmk

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: ./build/*.pdf

  compare:
    runs-on: ubuntu-26.04
    needs: [build]
    continue-on-error: true
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6
        with:
          sparse-checkout: ./scripts

      - name: Download latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ./old
          gh release download --dir ./old --repo ${{ github.repository }} --pattern "*.pdf"

      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: build
          path: ./new

      - name: Install diff tools
        run: sudo apt install -y diff-pdf-wx

      - name: Compare pdf
        run: |
          set -euxo pipefail
          ./scripts/compare.sh | tee report.txt

      - name: Upload diff
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: diff
          path: |
            ./old
            ./new
            ./diff
            ./report.txt

  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
