name: Build

on: [push, workflow_dispatch]

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Fix checkout in container (See https://github.com/actions/checkout/issues/1169)
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"

      - name: Generate gitinfo2 data
        run: ./third_party/gitinfo2/post-xxx-sample.sh && cat .git/gitHeadInfo.gin

      - name: Build PDF documents with latexmk
        run: latexmk && find ./build/ -type f ! -iname "*.pdf" -delete

      - name: Upload pdf artifact
        uses: actions/upload-artifact@v7
        with:
          name: pdf
          path: ./build/

  build_html:
    needs: build_pdf
    runs-on: ubuntu-latest
    container: pdf2htmlex/pdf2htmlex:0.18.8.rc2-master-20200820-ubuntu-20.04-x86_64
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y patch ttfautohint

      - name: Checkout pdf2htmlEX patch
        uses: actions/checkout@v7
        with:
          sparse-checkout: ./third_party/pdf2htmlEX

      - name: Patch pdf2htmlEX manifest
        run: patch /usr/local/share/pdf2htmlEX/manifest < /usr/local/share/pdf2htmlEX/manifest.patch

      - name: Download pdf artifact
        uses: actions/download-artifact@v8
        with:
          name: pdf
          path: ./

      - name: Build html with pdf2htmlEX
        run: |
          for FILE in *.pdf; do
            OUTPUT_FILE="$(basename "${FILE/%.pdf}.html")"
            pdf2htmlEX \
              --process-outline 0 \
              --dest-dir build \
              --bg-format svg \
              --external-hint-tool ttfautohint \
              "$FILE" "$OUTPUT_FILE"
          done

      - name: Upload html artifact
        uses: actions/upload-artifact@v7
        with:
          name: html
          path: ./build/

  compare:
    needs: build_pdf
    runs-on: ubuntu-26.04
    continue-on-error: true
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7
        with:
          sparse-checkout: ./scripts

      - name: Download latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ./old
          gh release download --dir ./old --repo ${{ github.repository }} --pattern "*.pdf"

      - name: Download pdf artifact
        uses: actions/download-artifact@v8
        with:
          name: pdf
          path: ./new

      - name: Install diff tools
        run: sudo apt install -y diff-pdf-wx

      - name: Compare pdf
        run: |
          set -euxo pipefail
          ./scripts/compare.sh | tee report.txt

      - name: Upload diff
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: diff
          path: |
            ./old
            ./new
            ./diff
            ./report.txt

  release:
    needs: [build_pdf, build_html]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write  # to make a release
    steps:
      - name: Download pdf artifact
        uses: actions/download-artifact@v8
        with:
          name: pdf

      - name: Download html artifact
        uses: actions/download-artifact@v8
        with:
          name: html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            *.pdf
            *.html
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest tag
        id: get_latest_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "latest_tag=$(gh release view --json tagName --jq '.tagName')" >> "$GITHUB_OUTPUT"

      - name: Check if this release was latest
        id: check_latest_release
        run: |
          echo "is_latest_release=$([ "${{steps.get_latest_tag.outputs.latest_tag}}" = "${{ github.ref_name }}" ] && echo 1 || echo 0)" >> "$GITHUB_OUTPUT"
    outputs:
      is_latest_release: ${{ steps.check_latest_release.outputs.is_latest_release }}

  deploy-pages:
    needs: release
    if: needs.release.outputs.is_latest_release
    runs-on: ubuntu-latest
    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source
    concurrency:
      # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
      # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
      group: "pages"
      cancel-in-progress: false
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
