name: Build PDF
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          submodules: true
          # fetch-depth: 0

      - name: Build PDF documents from LaTeX
        uses: ./.github/actions/texlive

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: build/*.pdf

  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
