# This is a workflow to build and deploy LaTeX sources

name: Build PDF from LaTeX

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout a repository
        uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: Build PDF documents from LaTeX
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: latexmk

      - name: Upload PDF documents
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/*.pdf
